monitoring:
  name: monitoring
  namespace: monitoring
  version: 45.7.1
  values:
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/ssl-passthrough: 'false'
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
        hosts:
          - grafana.mgmt.kub-poc.local
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.mgmt.kub-poc.local
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/ssl-passthrough: 'false'
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
        hosts:
          - prometheus.mgmt.kub-poc.local
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.mgmt.kub-poc.local
tinkstack:
  name: tink-stack
  namespace: tink-system
  version: 0.4.4
  values:
    smee:
      hostNetwork: true
      trustedProxies: 10.0.0.0/8
    hegel:
      trustedProxies: 10.0.0.0/8
    rufio:
      image: quay.io/tinkerbell/rufio:v0.4.1
    stack:
      enabled: true
      kubevip:
        enabled: false
      lbClass: kube-vip.io/kube-vip-class
      name: tink-stack
      selector:
        app: tink-stack
      service:
        type: LoadBalancer
