---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware-baremetal
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: tink-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/management/hardware-baremetal
    repoURL: git@github.com:ader1990/BMK.git
    targetRevision: baremetal_virtual
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware-virtual
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: tink-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/management/hardware-virtual
    repoURL: git@github.com:ader1990/BMK.git
    targetRevision: baremetal_virtual
