---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bm-auth-altra
  namespace: tink-system
spec:
  encryptedData:
    password: AgAfnIuLSz19ocT47Bm0vcUTAfrfs73Of9SVvqxngFLJYjEfoDZYPKwlMoV9SJa+f5IR8J/zwmjEEHxqSnt2UG02+dOb3WwK4DkfMtWYVHbapFLt8nwqCBnwCLdyY1px6QbCqxaJYdJLvTL2QSEBJxNkGpksgMaUGkeDBWCtCsXD3pisM2gwh5gJzQQqHGWDWSGvhG6pfE0l0TzrbkuxwcTSvakwn0qedFi5YVAVU1a7AeI2C1l5BshbsT45rsDX254MTwmJ5QBeklpoPxy5M0/Ty17t5MigkDn0XmJbE8H50+1tqpw3tBFGAmJfPOw/1D+XBjOS0OcTZRTIQ/H2sqyJPQuw0hiMv9+fN+vaud+/vytNJsi5zpDYdwotIPzpDtnNx09cPcwxZIMyiNDfeSu1jGG0kNy6PHDf9WXYVZm4b6eQfotfIlxN71DNYpETzsYw9DifkqstpM9V4hQwGJSrbxTI8ZGBiJh0lLuU6lCyVutvYX2yrXlGoGOjXGnRiBwtn4iEuQPH0MqRuTEqhblEwhKIFvVCTz1HjD1qzUd5tXew4LMvOc56mkAbTeVBM6mK37eLtczONf2TYX9Ktc8Jl9oHDYwIxjC6uJ6c2ZcwXQOq48+aPr+A1jOuBv4/XnuHZmqWl5wKwtojpzcaib6y8SSo+r+kkdAQ+ddJH+wJq/8VHOk3eH6ITfsqWldJqkT7KGubHw==
    username: AgCophL/D3mLcVA5juS113nYseCkKboyENOpkr3+1M9BSxRalGbOR2jTd5uyY8xOGCdj3tGslUF2JRoM5h2cTOHYYaWVg0jSLUz/cEHXC4N2ypljcTpvvV/4A6ZRbplO4ORtkSxi54zDzeMgctIJocA7fVGCMXfUBbNZV0aDMbBCjrS+OspXjMDkYs/f5kSxCnhmVNCGnqOOEncPv5AROCbbc7xwkRgmxmsJ7urrveEkdEDflGKMz1BD1ySn9BxzHECdLK5wbONeYCaWIIIdLr+WtzO25w7+eE55cDvXM7VnxJ3VSN+ijL2Hahg8sFl56YWo2quNP3ej4NoL6gsZ3GmhiDdPOfgqc2UrGuQIpN+rMTniZ6wadPcYc6nX3wQxZF8VXCTKV5WtO60yvqIBcd5/IpOud7zfAcjLqg2LtwDyFxWdNPhJQgqysALSVZ9tQHebH+V+RHjNaMITWBCziVSGF/MF0SDSw3mUeETKXSwFcsjsSfYRfEi5HZbxmMbPY3QOc+Qfq8xr9Ya8aluzGlpGSBywx//VSU+hEPN5o7h0jJoNvdObB6F6thdbKn7H4ZAcjNPurT9AIZsrw6VU7chqv+rfmXmUF8q5A054uvw8hV9MEtp/zu5y2oNyIsB2LnYrEpylLh9D+/uiu7Xu1kjv1h9Shy2rS2baQsIL9nN8SHMrorf97r45l48xS0r9ny2h1+SxkQ==
  template:
    metadata:
      creationTimestamp: null
      name: bm-auth-altra
      namespace: tink-system
    type: kubernetes.io/basic-auth
