---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bm-auth-altra
  namespace: tink-system
spec:
  encryptedData:
    password: AgAnmFMH4hfHNLcvCB9iFuWVgcO+QMhtjkoi8lCMhCESOneqHusHZWLDAOTMnZGgKjuRRfcU6LtbphU0bu3IpReyybQbWxZV4mdetcHwUJSUcV8pTA0gQ2UcD6zPr0IGmHy+3w67H/RskBFZW20Xl+3KxxrzI6hctKLuRpyguHncffsDouKSgtgsQwckabL9ueNERPhCw/exXHLmcmDFuBHdgAqywFkObxeCFtqJ4Irp05hIwQe8qqPrMMiM8wk2kUBCfQRFIanvnZCttdTPFBwz/n50bIXxf55H9O1U+4rylno/6wys0DRYPI4upqfLn03MPVdrYX3n/p5GuqhPLYOV4RsADKuoG4GNZe2WiTQELn2eyRKuMLuK5kceV/00ZfpgTc/Q1FOhMUfX2S2yEEXjYPjMV4Q0WRk0RTX9ODZog0/vTCsmp9O1y5Tkm8001aVKr0zN5IDVvM768frGh37aFFuH8oFz1S9tGeZJrg15h0xCRsVzoy0nZDBO3bjrsXiRNe+bK67g3v3v6lcfcjANaGjFCSuxE92TOLGaAsK/k26sRikf1GRaLYTZHkXHSeQq1pnGj6oaZUiuOoaMSIxnx3L6zF+fx74g5wp88R0F0G7jP9185t5f3M9pBqc3267LzKYXqgSLBcSRIlS26wGrajSRY8vjslrDoVS4sEGl3io01Jfm04xg254o2sJ9nM9NLtMmqw==
    username: AgAXh+wvlbOpbzpqV0gu+0nl2WdLtXL6Eu9/8HcEJhWE/b0Nk2VWfOhEIUxI/kQQF1O/6Ql5XZWdyijHKTcfUFxkWUBRUg9ApDHWee4gqQ21If2QmPpeBMWEh/f/zv3ZYD1t+DWLVbqmsa5ZSYXsAQPrpBNs+M8IhE4EDGRpj6Q0+D2oj2jYWJ2y8KkHSCu79+/7ePDCRX9Bg8qnURUrfs5y07AEh/uDLsFliSzE9hl00MwgQRNwFTCVERlYiqk6c+MV3fBHEfnuACu70AacpY86eAbnO4MWw5F3BBRNFQsA/Oy1DQBwDbKjiXfsej3OveRURhyO5IH3C1ejGFQQ3KIQQlpeaChZGWUoSQJJ96OLopQ0PKaWmtP9S9eY87WTf4byy9dbo0TxFPSolgi78/KQxG9XRj5acCxhUY5XI+FSjzVQy46PmRukAPEHbdgQmlek5MYv5AiuPL7ae/BoVcvP0EbkoCt/YTKzENGnccKrdPxUy6R20vtaoKwb94s8DLlJkpWcJ63i0OttEszPtbPgr0v2qQNer0LZI4GkVpOqNsf0joUiBZID1TYld4Ze/SdIAcrwvvmRZmwwo1eO6iCCTdNQP7SwlkpIDrbN6VKLZwO8DY+iPzEVVc4gudDkD8gdK9DTFwyaKXeENA089ncXBW+Qj4Eoqh2Ng+9L8p6dq2ayE1S41eemiySiYep5UbCo6tvsPw==
  template:
    metadata:
      creationTimestamp: null
      name: bm-auth-altra
      namespace: tink-system
    type: kubernetes.io/basic-auth
