---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: metallb
    name: kub-poc-admin@kub-poc
  project: default
  source:
    path: config/workload/metallb
    repoURL: git@github.com:ader1990/BMK.git
    targetRevision: baremetal_virtual
