---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.openstack_rabbitmq.name }}
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: {{ .Values.openstack_rabbitmq.namespace }}
    server: https://192.168.56.151:6443
  project: default
  source:
    chart: rabbitmq
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm
    targetRevision: {{ .Values.openstack_rabbitmq.version }}
    helm:
      valueFiles:
        - values.yaml
      values: |-
        {{- toYaml .Values.openstack_rabbitmq.values | nindent 8 }}
