---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.openstack_ingress_nginx.name }}
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: {{ .Values.openstack_ingress_nginx.namespace }}
    server: https://192.168.56.151:6443
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: {{ .Values.openstack_ingress_nginx.version }}
    helm:
      valueFiles:
        - values.yaml
      values: |-
        {{- toYaml .Values.openstack_ingress_nginx.values | nindent 8 }}
