---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.openstack_keystone.name }}
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: {{ .Values.openstack_keystone.namespace }}
    server: https://192.168.56.151:6443
  project: default
  source:
    repoURL: https://github.com/ader1990/openstack-helm
    path: keystone
    targetRevision: flatcar_june_2025
    helm:
      valueFiles:
        - values.yaml
      values: |-
        {{- toYaml .Values.openstack_keystone.values | nindent 8 }}
